name: Basic workflow

on: [workflow_dispatch]

env:
  output: 'Hello world!'

jobs:
  basic-workflow:
    runs-on: ubuntu-latest
    steps:

    - name: Write-output
      shell: pwsh
      run: |
          Write-Output "${{ env.output }}"